In [40]:
import pandas as pd
import os
import re

# Importing Raw Data

In [41]:
culturalspacesexcel='https://github.com/elstephens1216/PUBPOL542/blob/main/SeattleCulturalSpaceInventory.xlsx?raw=true'
culturalspaces=pd.read_excel(culturalspacesexcel)
culturalspaces

,Name,Phone,URL,Square Feet Total,Neighborhood,Organization Type,Dominant Discipline,Year of Occupation,Rent vs Own,Age of Current Building,...,Constituency over 50% one race,Specific Demographics and Community,Organization Leadership,Organization Artists,Closed Date,Closed?,Address,Location,Latitude,Longitude
0,Tmrw Party,NaN,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,Urban Wilderness Project,NaN,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,Bootstrap Music,NaN,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,Temple of Cairo,NaN,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,"(47.624282, -122.325052)",47.624282,-122.325052
4,Dynamic Sound Service,NaN,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,(206) 770-2700,www.empmuseum.org,140000.0,Seattle Center in Uptown,Y,Multi-use,2000.0,Other,2000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,325 5th Ave N Seattle WA 98109,"(47.62149775, -122.3482387)",47.621498,-122.348239
1210,The Project Room,(206) 499-9641,www.projectroomseattle.org,750.0,Capitol Hill,Y,Multi-use,2011.0,R,1912.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1315 E Pine St Seattle WA 98122,"(47.6151596, -122.3147172)",47.615160,-122.314717
1211,Seattle Pottery Supply,NaN,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,"(47.5749176, -122.3376252)",47.574918,-122.337625
1212,South Side Dance Force,(253) 639-5829,www.ssdanceforce.com,1200.0,NaN,N,Performance,2010.0,R,1987.0,...,NaN,NaN,NaN,NaN,NaN,0.0,706 Central Avenue South Kent WA 98032,"(47.375035, -122.22994)",47.375035,-122.229940
1213,University of Washington Jacob Lawrence Gallery,NaN,NaN,NaN,NaN,NaN,Arts/Cultural Training or Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,"(47.6585722, -122.3065403)",47.658572,-122.306540

# Renaming Columns

In [42]:
WhenYouFind='\\s+|\\d+|\\[|\\]'
replaceWith=''

In [43]:
culturalspaces.columns.str.replace(WhenYouFind,replaceWith,regex=True).str.lower()

Index(['name', 'phone', 'url', 'squarefeettotal', 'neighborhood',
       'organizationtype', 'dominantdiscipline', 'yearofoccupation',
       'rentvsown', 'ageofcurrentbuilding', 'lengthoflease(date)',
       'yearorganizationfounded', 'numberofpastfacilities',
       'stagesandtheaters', 'stage&theaterseats', 'galleryspace',
       'gallerysquarefeet', 'adacompliant', 'availableparking',
       'streetpresence', 'rentalspace', 'alcoholsales', 'organizationmission',
       'fundedbya&c', 'fundedbyculture',
       'stabilityindex(=verystable,=veryuncertain)',
       'controlindex(=veryincontrol,=veryoutofcontrol)',
       'constituencyover%onerace', 'specificdemographicsandcommunity',
       'organizationleadership', 'organizationartists', 'closeddate',
       'closed?', 'address', 'location', 'latitude', 'longitude'],
      dtype='object')

In [44]:
culturalspaces.columns[1::].str.replace(WhenYouFind,replaceWith,regex=True).str.lower()

Index(['phone', 'url', 'squarefeettotal', 'neighborhood', 'organizationtype',
       'dominantdiscipline', 'yearofoccupation', 'rentvsown',
       'ageofcurrentbuilding', 'lengthoflease(date)',
       'yearorganizationfounded', 'numberofpastfacilities',
       'stagesandtheaters', 'stage&theaterseats', 'galleryspace',
       'gallerysquarefeet', 'adacompliant', 'availableparking',
       'streetpresence', 'rentalspace', 'alcoholsales', 'organizationmission',
       'fundedbya&c', 'fundedbyculture',
       'stabilityindex(=verystable,=veryuncertain)',
       'controlindex(=veryincontrol,=veryoutofcontrol)',
       'constituencyover%onerace', 'specificdemographicsandcommunity',
       'organizationleadership', 'organizationartists', 'closeddate',
       'closed?', 'address', 'location', 'latitude', 'longitude'],
      dtype='object')

In [45]:
RenamedColumns=culturalspaces.columns[1::].str.replace(WhenYouFind,replaceWith,regex=True).str.lower()
RenamedColumns

Index(['phone', 'url', 'squarefeettotal', 'neighborhood', 'organizationtype',
       'dominantdiscipline', 'yearofoccupation', 'rentvsown',
       'ageofcurrentbuilding', 'lengthoflease(date)',
       'yearorganizationfounded', 'numberofpastfacilities',
       'stagesandtheaters', 'stage&theaterseats', 'galleryspace',
       'gallerysquarefeet', 'adacompliant', 'availableparking',
       'streetpresence', 'rentalspace', 'alcoholsales', 'organizationmission',
       'fundedbya&c', 'fundedbyculture',
       'stabilityindex(=verystable,=veryuncertain)',
       'controlindex(=veryincontrol,=veryoutofcontrol)',
       'constituencyover%onerace', 'specificdemographicsandcommunity',
       'organizationleadership', 'organizationartists', 'closeddate',
       'closed?', 'address', 'location', 'latitude', 'longitude'],
      dtype='object')

In [46]:
changes=dict(zip(culturalspaces.iloc[:,1::].columns,RenamedColumns))
changes

{'Phone': 'phone',
 'URL': 'url',
 'Square Feet Total': 'squarefeettotal',
 'Neighborhood': 'neighborhood',
 'Organization Type': 'organizationtype',
 'Dominant Discipline': 'dominantdiscipline',
 'Year of Occupation': 'yearofoccupation',
 'Rent vs Own': 'rentvsown',
 'Age of Current Building': 'ageofcurrentbuilding',
 'Length of Lease (Date)': 'lengthoflease(date)',
 ' Year Organization Founded': 'yearorganizationfounded',
 'Number of Past Facilities': 'numberofpastfacilities',
 'Stages and Theaters': 'stagesandtheaters',
 'Stage & Theater Seats ': 'stage&theaterseats',
 'Gallery Space': 'galleryspace',
 'Gallery Square Feet': 'gallerysquarefeet',
 'ADA Compliant': 'adacompliant',
 'Available Parking': 'availableparking',
 'Street Presence': 'streetpresence',
 'Rental Space ': 'rentalspace',
 'Alcohol Sales': 'alcoholsales',
 'Organization Mission': 'organizationmission',
 'Funded by A&C': 'fundedbya&c',
 'Funded by 4Culture': 'fundedbyculture',
 'Stability Index (5=very stable, 1=very uncertain)': 'stabilityindex(=verystable,=veryuncertain)',
 'Control Index (5=very in control, 1 = very out of control) ': 'controlindex(=veryincontrol,=veryoutofcontrol)',
 'Constituency over 50% one race': 'constituencyover%onerace',
 'Specific Demographics and Community': 'specificdemographicsandcommunity',
 'Organization Leadership': 'organizationleadership',
 'Organization Artists': 'organizationartists',
 'Closed Date': 'closeddate',
 'Closed?': 'closed?',
 'Address': 'address',
 'Location': 'location',
 'Latitude': 'latitude',
 'Longitude': 'longitude'}

In [47]:
culturalspaces.rename(columns=changes,inplace=True)
culturalspaces

,Name,phone,url,squarefeettotal,neighborhood,organizationtype,dominantdiscipline,yearofoccupation,rentvsown,ageofcurrentbuilding,...,constituencyover%onerace,specificdemographicsandcommunity,organizationleadership,organizationartists,closeddate,closed?,address,location,latitude,longitude
0,Tmrw Party,NaN,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,Urban Wilderness Project,NaN,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,Bootstrap Music,NaN,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,Temple of Cairo,NaN,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,"(47.624282, -122.325052)",47.624282,-122.325052
4,Dynamic Sound Service,NaN,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,(206) 770-2700,www.empmuseum.org,140000.0,Seattle Center in Uptown,Y,Multi-use,2000.0,Other,2000.0,...,NaN,NaN,NaN,NaN,NaN,0.0,325 5th Ave N Seattle WA 98109,"(47.62149775, -122.3482387)",47.621498,-122.348239
1210,The Project Room,(206) 499-9641,www.projectroomseattle.org,750.0,Capitol Hill,Y,Multi-use,2011.0,R,1912.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1315 E Pine St Seattle WA 98122,"(47.6151596, -122.3147172)",47.615160,-122.314717
1211,Seattle Pottery Supply,NaN,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,"(47.5749176, -122.3376252)",47.574918,-122.337625
1212,South Side Dance Force,(253) 639-5829,www.ssdanceforce.com,1200.0,NaN,N,Performance,2010.0,R,1987.0,...,NaN,NaN,NaN,NaN,NaN,0.0,706 Central Avenue South Kent WA 98032,"(47.375035, -122.22994)",47.375035,-122.229940
1213,University of Washington Jacob Lawrence Gallery,NaN,NaN,NaN,NaN,NaN,Arts/Cultural Training or Education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,"(47.6585722, -122.3065403)",47.658572,-122.306540

# Deleting unnecessary columns

In [48]:
del culturalspaces['phone']
culturalspaces

,Name,url,squarefeettotal,neighborhood,organizationtype,dominantdiscipline,yearofoccupation,rentvsown,ageofcurrentbuilding,lengthoflease(date),...,constituencyover%onerace,specificdemographicsandcommunity,organizationleadership,organizationartists,closeddate,closed?,address,location,latitude,longitude
0,Tmrw Party,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,Urban Wilderness Project,NaN,NaN,NaN,NaN,Multi-use,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,Bootstrap Music,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,Temple of Cairo,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,"(47.624282, -122.325052)",47.624282,-122.325052
4,Dynamic Sound Service,NaN,NaN,NaN,NaN,Studios,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,www.empmuseum.org,140000.0,Seattle Center in Uptown,Y,Multi-use,2000.0,Other,2000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,325 5th Ave N Seattle WA 98109,"(47.62149775, -122.3482387)",47.621498,-122.348239
1210,The Project Room,www.projectroomseattle.org,750.0,Capitol Hill,Y,Multi-use,2011.0,R,1912.0,2015.0,...,NaN,NaN,NaN,NaN,NaN,0.0,1315 E Pine St Seattle WA 98122,"(47.6151596, -122.3147172)",47.615160,-122.314717
1211,Seattle Pottery Supply,NaN,NaN,NaN,NaN,Service/Supply,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,"(47.5749176, -122.3376252)",47.574918,-122.337625
1212,South Side Dance Force,www.ssdanceforce.com,1200.0,NaN,N,Performance,2010.0,R,1987.0,2016.0,...,NaN,NaN,NaN,NaN,NaN,0.0,706 Central Avenue South Kent WA 98032,"(47.375035, -122.22994)",47.375035,-122.229940
1213,University of Washington Jacob Lawrence Gallery,NaN,NaN,NaN,NaN,Arts/Cultural Training or Education,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,"(47.6585722, -122.3065403)",47.658572,-122.306540

In [49]:
del culturalspaces['url']
del culturalspaces['squarefeettotal']
del culturalspaces['rentvsown']
del culturalspaces['organizationtype']

In [50]:
del culturalspaces['ageofcurrentbuilding']
del culturalspaces['lengthoflease(date)']
del culturalspaces['yearorganizationfounded']

In [51]:
del culturalspaces['numberofpastfacilities']
del culturalspaces['stagesandtheaters']
del culturalspaces['stage&theaterseats']
del culturalspaces['galleryspace']

In [52]:
del culturalspaces['gallerysquarefeet']
del culturalspaces['adacompliant']
del culturalspaces['availableparking']
del culturalspaces['streetpresence']
del culturalspaces['rentalspace']

In [53]:
del culturalspaces['organizationmission']
del culturalspaces['alcoholsales']
del culturalspaces['fundedbya&c']
del culturalspaces['fundedbyculture']

In [54]:
del culturalspaces['stabilityindex(=verystable,=veryuncertain)']
del culturalspaces['controlindex(=veryincontrol,=veryoutofcontrol)']
del culturalspaces['constituencyover%onerace']

In [55]:
del culturalspaces['specificdemographicsandcommunity']
del culturalspaces['organizationleadership']
del culturalspaces['organizationartists']
del culturalspaces['location']
del culturalspaces['latitude']
del culturalspaces['longitude']

In [56]:
culturalspaces

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address
0,Tmrw Party,NaN,Multi-use,NaN,NaN,0.0,NaN
1,Urban Wilderness Project,NaN,Multi-use,NaN,NaN,0.0,NaN
2,Bootstrap Music,NaN,Studios,NaN,NaN,0.0,NaN
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102
4,Dynamic Sound Service,NaN,Studios,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134
1212,South Side Dance Force,NaN,Performance,2010.0,NaN,0.0,706 Central Avenue South Kent WA 98032
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...

# Creating and cleaning zipcode column

Testing creating zipcode column

In [57]:
CStest=culturalspaces.copy()

In [58]:
CStest['zipcode'] = CStest['address'].str.extract(r'(\d{5}\-?)')

In [59]:
CStest

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode
0,Tmrw Party,NaN,Multi-use,NaN,NaN,0.0,NaN,NaN
1,Urban Wilderness Project,NaN,Multi-use,NaN,NaN,0.0,NaN,NaN
2,Bootstrap Music,NaN,Studios,NaN,NaN,0.0,NaN,NaN
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102
4,Dynamic Sound Service,NaN,Studios,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134
1212,South Side Dance Force,NaN,Performance,2010.0,NaN,0.0,706 Central Avenue South Kent WA 98032,98032
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105

Creatng zipcode column:

In [80]:
culturalspaces['zipcode'] = culturalspaces['address'].str.extract(r'(\d{5}\-?)')
culturalspaces

<ipython-input-80-a038fbf02394>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  culturalspaces['zipcode'] = culturalspaces['address'].str.extract(r'(\d{5}\-?)')

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104
...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134
1212,South Side Dance Force,NaN,Performance,2010.0,NaN,0.0,706 Central Avenue South Kent WA 98032,98032
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105

Deleting NaN zipcodes

In [63]:
culturalspaces = culturalspaces[culturalspaces['zipcode'].notna()]
culturalspaces

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104
...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134
1212,South Side Dance Force,NaN,Performance,2010.0,NaN,0.0,706 Central Avenue South Kent WA 98032,98032
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105

Deleting zipcodes outside of Seattle

In [84]:
culturalspaces['inSeattle'] = culturalspaces.zipcode.str.startswith('981')

<ipython-input-84-e20a38d590c7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  culturalspaces['inSeattle'] = culturalspaces.zipcode.str.startswith('981')

In [85]:
culturalspaces

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1212,South Side Dance Force,NaN,Performance,2010.0,NaN,0.0,706 Central Avenue South Kent WA 98032,98032,False
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

In [86]:
culturalspacesseattle=culturalspaces[culturalspaces.inSeattle==True]

In [87]:
culturalspacesseattle

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1207,Q,Interbay,Visual,2002.0,NaN,0.0,3223 15th Ave W Seattle WA 98119,98119,True
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

Testing - deleting cultural spaces that have closed

In [89]:
CStest2=culturalspacesseattle.copy()

In [90]:
CStest2=CStest2[CStest2["closeddate"]!='Nan']

In [91]:
CStest2

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1207,Q,Interbay,Visual,2002.0,NaN,0.0,3223 15th Ave W Seattle WA 98119,98119,True
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

Testing - deleting extraneous characters in zipcode column

In [103]:
CStest3=culturalspacesseattle.copy()

In [121]:
nohyphens=CStest3.replace("-","")
nohyphens

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1207,Q,Interbay,Visual,2002.0,NaN,0.0,3223 15th Ave W Seattle WA 98119,98119,True
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multiuse,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multiuse,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

Deleting extraneous zipcodes

In [133]:
cleanCSseattle=culturalspacesseattle.copy()
cleanCSseattle=cleanCSseattle.replace("-","")
cleanCSseattle

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1207,Q,Interbay,Visual,2002.0,NaN,0.0,3223 15th Ave W Seattle WA 98119,98119,True
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

# Aggregating

In [134]:
cleanCSseattle

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,zipcode,inSeattle
3,Temple of Cairo,NaN,Service/Supply,NaN,NaN,0.0,507 E Mercer Seattle WA 98102,98102,True
5,Keys on Main,NaN,Music,NaN,NaN,0.0,11 Roy St Seattle WA 98109,98109,True
6,Canlis Glass,Uptown,Visual,2005.0,NaN,0.0,3131 Western Ave #329 Seattle WA 98121,98121,True
7,Green Lake Community Center,NaN,Community Center,NaN,NaN,0.0,7201 East Green Lake Dr N Seattle WA 98115,98115,True
8,Seattle Metropolitan Police Museum,NaN,Education,NaN,NaN,0.0,317 3rd Ave South Seattle WA 98104,98104,True
...,...,...,...,...,...,...,...,...,...
1207,Q,Interbay,Visual,2002.0,NaN,0.0,3223 15th Ave W Seattle WA 98119,98119,True
1209,Seattle Center EMP and Sky Church,Seattle Center in Uptown,Multi-use,2000.0,NaN,0.0,325 5th Ave N Seattle WA 98109,98109,True
1210,The Project Room,Capitol Hill,Multi-use,2011.0,NaN,0.0,1315 E Pine St Seattle WA 98122,98122,True
1211,Seattle Pottery Supply,NaN,Service/Supply,NaN,NaN,0.0,35 S Hanford St Seattle WA 98134,98134,True
1213,University of Washington Jacob Lawrence Gallery,NaN,Arts/Cultural Training or Education,NaN,NaN,0.0,Art Building Room 132 West Stevens Way NE Seat...,98105,True

Testing - aggregating cultural spaces by zipcode

In [122]:
aggregatingtest2=nohyphens.groupby('zipcode').count()

In [123]:
aggregatingtest2

,Name,neighborhood,dominantdiscipline,yearofoccupation,closeddate,closed?,address,inSeattle
zipcode,,,,,,,,
98101,56,36,56,29,0,55,56,56
98102,20,8,20,8,2,19,20,20
98103,80,50,80,47,3,80,80,80
98104,88,57,88,48,4,88,88,88
98105,65,27,65,25,0,63,65,65
98106,9,6,9,6,0,9,9,9
98107,37,19,37,18,2,37,37,37
98108,36,18,36,18,1,35,36,36
98109,55,34,55,34,3,55,55,55
98112,16,8,16,5,1,16,16,16
98115,27,11,27,9,0,27,27,27
98116,20,10,20,8,0,20,20,20
98117,13,8,13,6,1,13,13,13
98118,37,24,37,23,0,35,37,37
98119,19,9,19,7,0,19,19,19
98121,41,26,41,22,3,40,41,41
98122,93,52,93,49,7,93,93,93
98125,4,3,4,2,0,4,4,4
98126,9,4,9,4,0,9,9,9
98133,4,1,4,1,0,4,4,4
98134,25,8,25,8,0,25,25,25
98136,8,7,8,7,0,8,8,8
98144,28,14,28,15,0,27,28,28
98145,1,1,1,1,0,1,1,1
98146,4,1,4,3,0,4,4,4
98148,1,0,1,0,0,1,1,1
98154,1,0,1,0,0,1,1,1
98155,4,0,4,3,0,4,4,4
98166,7,0,7,6,0,7,7,7
98168,2,1,2,1,0,1,2,2
98188,1,0,1,1,0,1,1,1
98195,15,6,15,6,0,15,15,15
98198,3,0,3,2,0,3,3,3
98199,8,4,8,4,0,8,8,8

In [138]:
cleanCSseattle=aggregatingtest2.copy()
del cleanCSseattle['neighborhood']
del cleanCSseattle['dominantdiscipline']
del cleanCSseattle['yearofoccupation']
del cleanCSseattle['closeddate']
del cleanCSseattle['closed?']
del cleanCSseattle['address']
del cleanCSseattle['inSeattle']
cleanCSseattle

         Name
zipcode
98101      56
98102      20
98103      80
98104      88
98105      65
98106       9
98107      37
98108      36
98109      55
98112      16
98115      27
98116      20
98117      13
98118      37
98119      19
98121      41
98122      93
98125       4
98126       9
98133       4
98134      25
98136       8
98144      28
98145       1
98146       4
98148       1
98154       1
98155       4
98166       7
98168       2
98188       1
98195      15
98198       3
98199       8

In [139]:
cleanCSseattle.columns=['culturalspaces']

In [140]:
cleanCSseattle

         culturalspaces
zipcode
98101                56
98102                20
98103                80
98104                88
98105                65
98106                 9
98107                37
98108                36
98109                55
98112                16
98115                27
98116                20
98117                13
98118                37
98119                19
98121                41
98122                93
98125                 4
98126                 9
98133                 4
98134                25
98136                 8
98144                28
98145                 1
98146                 4
98148                 1
98154                 1
98155                 4
98166                 7
98168                 2
98188                 1
98195                15
98198                 3
98199                 8

In [142]:
cleanCSseattle.to_excel(r'C:\Users\elste_000\Documents\aggculturalspaces-final.xlsx')